# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Varun Garg
tagline:             'What if there were no hypothetical questions?'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://mamakancha.github.io
paginate:            5

# About/contact
author:
  name:              Varun Garg
  url:               http://mamakancha.github.io
  email:             varun.garg03@gmail.com

# Custom vars
version:             1.0.0
